### ISSUE TITLE
WCMP --> Vendor section setpassword is throwing exception. can we get 

### ISSUE THREAD

**Issue by kapilkoujalagi** [multivendorx/dc-woocommerce-multi-vendor#1100]
WCMP --> Vendor section setpassword is throwing exception. can we get not working

**Comment by cool-raju** [comment]
no such issue in our end

**Comment by moumitahalder** [comment]
@kapilkoujalagi please check on your end also.

**Comment by cool-raju** [comment]
hope no such issue found
Thanks
