### ISSUE TITLE
Vendor assign Issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/dc-woocommerce-multi-vendor#1105]
After updating wcmp to 3.8.12, i am no longer able to assign a vendor to a product. When typing the name of a vendor in choose vendor, it stuck on “looking for” and never show any.

https://watch.screencastify.com/v/GNXQZGvViQAUSRWy0hZu

src : https://wc-marketplace.com/support-forum/topic/unable-to-assign-a-vendor-to-a-product-after-update/

**Comment by cool-raju** [comment]
fixed

**Comment by craftedsro** [comment]
Hi I have same issue

**Comment by cool-raju** [comment]
we have added d fix on main branch. please use it. @craftedsro 
Download from here https://github.com/wcmarketplace/dc-woocommerce-multi-vendor

**Comment by rachidsebaa** [comment]
Still got the issue, even after updated the commisssion.js and commission.min.js files
