### ISSUE TITLE
vendor name assign issue

### ISSUE THREAD

**Issue by moumitahalder** [multivendorx/dc-woocommerce-multi-vendor#1107]
*To Recreate
- Create Two Vendor. Set their shop name as Shop1 and Shop2
- Now from admin end, add a product
- Under Vendor tab, search vendor name by Shop2, you can only see Shop1 in the result.

* Expected Flow
- When we are searching the vendor name by Shop, it should display both name i.e. Shop1 and Shop2
- When  we are searching the vendor name by Shop2, it should display  Shop2

**Comment by BKUSA** [comment]
Is there an ETA?

**Comment by BKUSA** [comment]
Hello?
