### ISSUE TITLE
Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in /public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/shipping-gateways/class-mvx-country-shipping-method.php:365 

### ISSUE THREAD

**Issue by ikishorkumar** [multivendorx/dc-woocommerce-multi-vendor#1118]
i am facing this issue while i login into it via my account page as admin 
 
 i get this error critical error. 
 
 
 Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, string given in /www/sitename/public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/shipping-gateways/class-mvx-country-shipping-method.php:365 Stack trace: #0 /www/sitename/public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/shipping-gateways/class-mvx-country-shipping-method.php(141): MVX_Shipping_By_Country->calculate_per_seller(Array, 'US', 'CA') #1 /www/sitename/public/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php(233): MVX_Shipping_By_Country->calculate_shipping(Array) #2 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(348): WC_Shipping_Method->get_rates_for_package(Array) #3 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-shipping.php(260): WC_Shipping->calculate_shipping_for_package(Array, 10) #4 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1423): WC_Shipping->calculate_shipping(Array) #5 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(339): WC_Cart->calculate_shipping() #6 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(850): WC_Cart_Totals->get_shipping_from_cart() #7 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(144): WC_Cart_Totals->calculate_shipping_totals() #8 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php(134): WC_Cart_Totals->calculate() #9 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1401): WC_Cart_Totals->__construct(Object(WC_Cart)) #10 /www/sitename/public/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(212): WC_Cart->calculate_totals() #11 /www/sitename/public/wp-includes/class-wp-hook.php(308): WC_Cart_Session->get_cart_from_session('') #12 /www/sitename/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #13 /www/sitename/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #14 /www/sitename/public/wp-settings.php(645): do_action('wp_loaded') #15 /www/sitename/public/wp-config.php(103): require_once('/www/sitename...') #16 /www/sitename/public/wp-load.php(50): require_once('/www/sitename...') #17 /www/sitename/public/wp-blog-header.php(13): require_once('/www/sitename..') #18 /www/public/index.php(17): require('/www/sitename...') #19 {main}
 /public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/shipping-gateways/class-mvx-country-shipping-method.php on line 365

**Comment by ikishorkumar** [comment]
The code snippet you provided is responsible for checking if the `$destination_country` exists as a key in the `$mvx_country_rates` array. If it does, the corresponding value is assigned to `$price[$vendor_id]['state_rates']`. Otherwise, a default value of 0 is assigned.

Based on the error message you shared, it seems that the `$mvx_country_rates` variable is not an array, but a string. To fix the issue, you need to ensure that `$mvx_country_rates` is an array before attempting to access its values using array keys.

You can modify the code as follows:

Copy the Code:


if (is_array($mvx_country_rates)) {
    if (!array_key_exists($destination_country, $mvx_country_rates)) {
        $price[$vendor_id]['state_rates'] = isset($mvx_country_rates['everywhere']) ? floatval($mvx_country_rates['everywhere']) : 0;
    } else {
        $price[$vendor_id]['state_rates'] = (isset($mvx_country_rates[$destination_country])) ? floatval($mvx_country_rates[$destination_country]) : 0;
    }
} else {
    // Handle the case where $mvx_country_rates is not an array, such as assigning a default value.
    // Example:
    $price[$vendor_id]['state_rates'] = 0;
}


In the modified code, an additional check `is_array($mvx_country_rates)` is added before attempting to access the values using `array_key_exists()`. If `$mvx_country_rates` is not an array, you can handle it accordingly. In the example above, a default value of 0 is assigned to `$price[$vendor_id]['state_rates']` in case `$mvx_country_rates` is not an array.

Make sure to replace the code in line 65 of the file `/www/sitename/public/wp-content/plugins/dc-woocommerce-multi-vendor/classes/shipping-gateways/class-mvx-country-shipping-method.php` with the modified code.

After making these changes, save the file and test your application to see if the error is resolved.

**Comment by moumitahalder** [comment]
Follow this https://github.com/multivendorx/MultiVendorX/issues/406
