### ISSUE TITLE
Vendor Unable to make withdraw request

### ISSUE THREAD

**Issue by ikishorkumar** [multivendorx/dc-woocommerce-multi-vendor#1123]
the vendor unable to make withdraw request for payment

vendor has PayPal payout method and email attached

**Comment by Sangi0** [comment]
We have checked this on our end . There should not be any such issue if you have configured PayPal payout correctly .  Kindly fetch the credentials accordingly . You can go through our doc for your reference https://multivendorx.com/docs/knowledgebase/paypal-payout/
